name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies for Kivy
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libmtdev1 \
            libgl1-mesa-dev \
            xserver-xorg \
            xvfb

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
          pip uninstall kivymd -y
          pip install kivymd==1.1.1

      - name: Recreate Firebase Service Account JSON
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > offerings2rang-firebase-adminsdk-fbsvc-a746c6d5e3.json

      - name: Run Tests (Headless Mode)
        run: xvfb-run python pooplog.py
